GET http://localhost:5173/api/comments

POST http://localhost:5173/api/comments
Content-Type: application/json

{
    "text": "New comment"
}

GET http://localhost:5173/api/comments/1

PATCH http://localhost:5173/api/comments/3
Content-Type: application/json

{
    "text": "Updated comment."
}


